### ISSUE TITLE
Not working for Plone 4

### ISSUE THREAD

**Issue by fongtech** [collective/collective.webhook#1]
Seem like not workable for Plone4.

Got this error:
from plone.app.contentrules.actions import ActionAddForm
ImportError: cannot import name ActionAddForm

Thanks for your amazing work.

**Comment by datakurre** [comment]
Thanks. Plone 4 issue is probably that Plone 5 provides z3c.form based content rule base forms not available yet on Plone.

**Comment by datakurre** [comment]
I have need for Plone 4 support for myself, so I might do this this week.

**Comment by datakurre** [comment]
@fongtech 0.3.0 should work on Plone 4.3 too

**Comment by fongtech** [comment]
Thanks, shall give feedback if any.
